name: CI_codestyle

on:
  pull_request:
    branches:
    - master

jobs:
  codestyle:    
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4    
    - name: Test coding style
      run: |
        bash ./buildscripts/ci/linux/checkcodestyle.sh
